DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilations_to_event CASCADE;
DROP TABLE If EXISTS requests CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    name  VARCHAR(250)        NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    name VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT REFERENCES categories (id) NOT NULL,
    confirmed_Requests BIGINT,
    create_date        TIMESTAMP,
    description        VARCHAR(2000),
    event_date         TIMESTAMP                         NOT NULL,
    initiator_id       BIGINT REFERENCES users (id)      NOT NULL,
    lat                NUMERIC                           NOT NULL,
    lon                NUMERIC                           NOT NULL,
    paid               BOOLEAN,
    participant_limit  INTEGER DEFAULT 0,
    published_date     TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE,
    status             VARCHAR,
    title              VARCHAR(120)                           NOT NULL,
    views              BIGINT
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    event_id     BIGINT REFERENCES events (id) NOT NULL,
    requester_id BIGINT REFERENCES users (id)  NOT NULL,
    create_date  TIMESTAMP,
    status       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    pinned BOOLEAN NOT NULL,
    title(50)  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_to_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    event_id       BIGINT REFERENCES events (id)       NOT NULL,
    compilation_id BIGINT REFERENCES compilations (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    comment      VARCHAR                       NOT NULL,
    event_id     BIGINT REFERENCES events (id) NOT NULL,
    author_id    BIGINT REFERENCES users (id)  NOT NULL,
    created_date TIMESTAMP
);